name: CI
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - migrations/**
      - src/**
      - twilight/**
      - .rustfmt.toml
      - Cargo.lock
      - Cargo.toml
      - build.rs
  pull_request:
    branches:
      - main
    paths:
      - migrations/**
      - src/**
      - twilight/**
      - .rustfmt.toml
      - Cargo.lock
      - Cargo.toml
      - build.rs
permissions:
  contents: read
env:
  RUSTFLAGS: -Cdebuginfo=1
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install rust
        id: install_rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Fetch cache
        uses: Swatinem/rust-cache@v2
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Rustfmt
        if: always() && steps.install_rust.outcome == 'success'
        run: cargo fmt -- --check
